// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/api/alive/index.tsx";
import * as $5 from "./routes/api/jokes/index.tsx";
import * as $6 from "./routes/countdown.tsx";
import * as $7 from "./routes/github/[username].tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/helloworld.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/index_get.tsx";
import * as $12 from "./routes/search.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/GenStory.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/about.tsx": $3,
    "./routes/api/alive/index.tsx": $4,
    "./routes/api/jokes/index.tsx": $5,
    "./routes/countdown.tsx": $6,
    "./routes/github/[username].tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/helloworld.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/index_get.tsx": $11,
    "./routes/search.tsx": $12,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/GenStory.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
